stages:
  - build

build:
  image: ubuntu:xenial
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make appimage
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA:0:8}"
    expire_in: 4 week
    paths:
      - build/*.AppImage

