stages:
  - build

build:
  image: ubuntu:xenial
  stage: build
  script:
    - apt update -y && apt upgrade -y && apt install -y build-essential git cmake libusb-1.0-0-dev pkgconf swig libcppunit-dev python2.7 libudev-dev python-cheetah wget libxrender-dev libice-dev libsm6 autoconf unzip libtool-bin 
    - wget https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.sh && chmod +x cmake-3.12.1-Linux-x86_64.sh
    - mkdir -p /opt/cmake && sh ./cmake-3.12.1-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
    - ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
    - cmake --version
    - rm -rf .git
    - rm cmake-3.12.1-Linux-x86_64.sh
    - mkdir build
    - cd build
    - cmake ../
    - grep -rnw . -e "Sebastian" || sh -c "true"
    - env
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
    - make appimage
    - echo "$SSH_DEPLOY_KEY" > id_rsa
    - mkdir -p /root/.ssh && echo "move2radio.lrt.mw.tum.de,129.187.219.19 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGGGGcNlYAHUns3lzPs6oh9E/6l8KSPckOGGA3t2w6khD7m4jdesEz2JRj9X2W08/vGOzF6w1P+rSLK8xbTYVls=" > /root/.ssh/known_hosts
    - scp -i id_rsa Gnuradio_Companion-x86_64.AppImage deploy@move2radio.lrt.mw.tum.de:/home/deploy/move2radio-staging-x86_64.AppImage

